### PR TITLE
maintain image order

### PR DESCRIPTION
**Pull request by omzy83**

### CODE REVIEW

**Comment by omzy83** [comment]
The test failed, I think because now that the Gallery will maintain the order, the 6th image will be a different one to the one the test is looking for.

**Comment by jgrossi** [comment]
@omzy83 then can you update the tests? can't us change the order just to make the test passing?

**Comment by omzy83** [comment]
@jgrossi test updated and passes successfully, please can you check and merge?

**Comment by jgrossi** [comment]
sorry about being late 😎thanks for the PR!

**Pull request merged**
