### PR TITLE
Update to corcel 3.0

### LINKED ISSUE #79: Support for corcel 3.0
How to make it compatible with latest release of [Corcel](https://github.com/corcel/corcel).
Just change `"jgrossi/corcel": "~2.1"` to `"jgrossi/corcel": "~3.0"` ?

### PR DESCRIPTION
**Pull request by hebbet**
fixes #79

### CODE REVIEW

**Comment by zeroiszero** [comment]
travis build failed with the command `mkdir -p build/logs` in `.travis.yml`. May I know what is use of that ?

**Comment by hebbet** [comment]
> travis build failed with the command mkdir -p build/logs in .travis.yml

Nope. the exit code of `mkdir -p` is 0, so successful.

mkdir -p creates folders, including the parent folder if it doesn't exist.

**Comment by zeroiszero** [comment]
@hebbet , I made another pull request #81 that will fix the travis issue (phpunit 8 compatibility)

**Comment by jgrossi** [comment]
@hebbet hey thanks for the hard work
I fixed the Travis build on branch `pr-80` that includes your changes on this PR plus required changed to make it working
can you change the base the base branch from this PR to `pr-80` please? it has your changes already
thanks!

**Comment by hebbet** [comment]
Bildschirmfoto von 2019-09-13 15-15-45

when i try to change that, i get that error.

**Comment by zeroiszero** [comment]
@hebbet , i think you need to sync with the branch `pr-80`.

**Comment by jgrossi** [comment]
@hebbet this PR's base branch is your `develop` one. can you change that to another `pr-80` branch? then I can push changes to it to update the PR and merge it here, thanks!

**Comment by hebbet** [comment]
I don't see an option for that

Junior Grossi <notifications@github.com> schrieb am Fr., 13. Sept. 2019,
15:36:

**Comment by jgrossi** [comment]
@hebbet ok gonna close this PR and raise another one based on `pr-80` branch. thanks for the work

**Pull request closed without merging**
